schema_version = "1.0.0"
id = "paste_clipboard_image"
tagline = "Paste images from clipboard directly into Shader Editor nodes"
name = "Paste Clipboard Image"
version = "1.0.0"
license = ["MIT"]
maintainer = "EZbacaon"
type = "add-on"
tags = ["Node", "Workflow", "Images", "Clipboard"]
blender_version_min = "4.4.0"
description = "Ctrl+V in Shader Editor to paste clipboard images into an Image Texture node."

[permissions]
filesystem = "true"
network = "true"
